# Introduction {#intro}

This book will focuses on project-based learning of Data Science as applied to various micro-economic data:

-   Industry-specific data - marketing and sales

The main idea is to introduce corporate sectors (motor, retail, logistic industry) to best practice approaches to leverage their business operations through use of Data Science. All the illustrations will be using case studies to make you understand how best can you implement Data Science to solve business problems. The table below shows various steps as applied to different companies.[@eddie2022]

## Import data (extract,load)

This section deals with extraction of data from various sources depending on the use-case.

## Data wrangling (transform)

This outline steps to uncover useful insights from the data, thus including transformation,

## Model selection (modeling)

Various approaches are used to build machine learning models based on the use-cases.

## Evaluation

Different machine learning models have different ways to evaluate their performance.

## Deployment

For machine learning models to be useful, one needs to put them into production so as to add value to various businesses.
